---
sudo: required
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
services:
  - docker
before_install:
  - sudo apt-get update
  - sudo apt-get install libssl-dev libffi-dev
  - sudo -H python -m pip install ansible docker molecule
  - sudo python -m pip install six==1.12.0
  - sudo python -m pip install cryptography==2.2.2 testinfra
script:
  - molecule test
